In [2]:
#Exemplu de invatare hebbiana

import numpy as np

w = [1,-1,0,0.5]

net = 0
x = 0        #Numarul de iteratii
c = 1        #Rata de invatare

while x < 10:
    
    x1 = [1,-2,1.5,0]
    x2 = [1,-0.5,-2,-1.5]
    x3 = [0,1,-1,1.5]
    

    print("Se aplica x1:")
    
    net = np.dot(w,x1)
    fnet = [y * np.sign(net) for y in x1]
    w = np.add(w,fnet)
    print(w,"\n")


    print("Se aplica x2:")
    
    net = np.dot(w,x2)
    fnet = [y * np.sign(net) for y in x2]
    w = np.add(w,fnet)
    print(w,"\n")


    print("Se aplica x3:")
    
    net = np.dot(w,x3)
    fnet = [y * np.sign(net) for y in x3]
    w = np.add(w,fnet)
    print(w,"\n")
    
    x = x + 1

Se aplica x1:
[ 2.  -3.   1.5  0.5] 

Se aplica x2:
[ 1.  -2.5  3.5  2. ] 

Se aplica x3:
[ 1.  -3.5  4.5  0.5] 

Se aplica x1:
[ 2.  -5.5  6.   0.5] 

Se aplica x2:
[ 1. -5.  8.  2.] 

Se aplica x3:
[ 1.  -6.   9.   0.5] 

Se aplica x1:
[ 2.  -8.  10.5  0.5] 

Se aplica x2:
[ 1.  -7.5 12.5  2. ] 

Se aplica x3:
[ 1.  -8.5 13.5  0.5] 

Se aplica x1:
[  2.  -10.5  15.    0.5] 

Se aplica x2:
[  1. -10.  17.   2.] 

Se aplica x3:
[  1.  -11.   18.    0.5] 

Se aplica x1:
[  2.  -13.   19.5   0.5] 

Se aplica x2:
[  1.  -12.5  21.5   2. ] 

Se aplica x3:
[  1.  -13.5  22.5   0.5] 

Se aplica x1:
[  2.  -15.5  24.    0.5] 

Se aplica x2:
[  1. -15.  26.   2.] 

Se aplica x3:
[  1.  -16.   27.    0.5] 

Se aplica x1:
[  2.  -18.   28.5   0.5] 

Se aplica x2:
[  1.  -17.5  30.5   2. ] 

Se aplica x3:
[  1.  -18.5  31.5   0.5] 

Se aplica x1:
[  2.  -20.5  33.    0.5] 

Se aplica x2:
[  1. -20.  35.   2.] 

Se aplica x3:
[  1.  -21.   36.    0.5] 

Se aplica x1:
[  2.  -23.   37.5   0.5] 

Se

In [1]:
import numpy as np

w = [1,-1]

net = 0
x = 0        #Numarul de iteratii
c = 1        #Rata de invatare

while x < 2:
    
    x1 = [1,-2]
    x2 = [0,1]
    x3 = [2,3]
    x4 = [1,-1]
    

    print("Se aplica x1:")
    
    net = np.dot(w,x1)
    fnet = [y * np.sign(net) for y in x1]
    w = np.add(w,fnet)
    print(w,"\n")


    print("Se aplica x2:")
    
    net = np.dot(w,x2)
    fnet = [y * np.sign(net) for y in x2]
    w = np.add(w,fnet)
    print(w,"\n")


    print("Se aplica x3:")
    
    net = np.dot(w,x3)
    fnet = [y * np.sign(net) for y in x3]
    w = np.add(w,fnet)
    print(w,"\n")
    
    
    print("Se aplica x4:")
    
    net = np.dot(w,x4)
    fnet = [y * np.sign(net) for y in x4]
    w = np.add(w,fnet)
    print(w,"\n")
    
    x = x + 1

Se aplica x1:
[ 2 -3] 

Se aplica x2:
[ 2 -4] 

Se aplica x3:
[ 0 -7] 

Se aplica x4:
[ 1 -8] 

Se aplica x1:
[  2 -10] 

Se aplica x2:
[  2 -11] 

Se aplica x3:
[  0 -14] 

Se aplica x4:
[  1 -15] 

