In [1]:
# Invatarea unui neuron prin regula perceptronului

import numpy as np

w1 = np.array([0,1,0])[np.newaxis] # Ponderea

c = 0.1 # Rata de invatare

d1 = -1 # Output-ul target
d2 = 1 # Output-ul target


z = 0 # iteratorul

while z < 5:
    
    x1 = [2,1,-1] # Vector de intrare
    x2 = [0,-1,-1] # Vector de intrare
    
    print("Se aplica x1 : ")
    
    net = np.dot(w1,x1) # Produsul scalar
    print("Net la pasul 1 este: ",net)
    
    fnet = np.sign(net) # Functia sign a produsului scalar
    
    if fnet[0] != d1:
        print("Are loc o corectie a ponderilor!")
        y = c*(d1-fnet[0]) # Produsul dintre rata de invatare si diferenta dintre output-ul target d1 si output-ul obtinut
        x1 = [x * y for x in x1] # Inmultirea vectorului de intrare x1 cu produsul obtinut la y
        w1 = np.add(w1,x1) # Modificarea lui w1 
        print("Dupa corectia ponderei w1 este:")
        print(w1.T,"\n")
    else:
        print("Nu are loc nicio corectie","\n")
        
        
        
        
    print("Se aplica x2")
    
    net = np.dot(w1,x2) # Produsul scalar
    print("Net la pasul 2 este: ",net)
    
    fnet = np.sign(net) # Functia sign a produsului scalar
    
    if fnet[0] != d2:
        print("Are loc o corectie a ponderilor!")
        y = c*(d2-fnet[0])  # Produsul dintre rata de invatare si diferenta dintre output-ul target d2 si output-ul obtinut
        x2 = [x * y for x in x2]  # Inmultirea vectorului de intrare x2 cu produsul obtinut la y
        w1 = np.add(w1,x2) # Modificarea lui w2
        print("Dupa corectia ponderei w1 este:")
        print(w1.T,"\n")
    else:
        print("Nu are loc nicio corectie","\n")
    z = z + 1


Se aplica x1 : 
Net la pasul 1 este:  [1]
Are loc o corectie a ponderilor!
Dupa corectia ponderei w1 este:
[[-0.4]
 [ 0.8]
 [ 0.2]] 

Se aplica x2
Net la pasul 2 este:  [-1.]
Are loc o corectie a ponderilor!
Dupa corectia ponderei w1 este:
[[-0.4]
 [ 0.6]
 [ 0. ]] 

Se aplica x1 : 
Net la pasul 1 este:  [-0.2]
Nu are loc nicio corectie 

Se aplica x2
Net la pasul 2 este:  [-0.6]
Are loc o corectie a ponderilor!
Dupa corectia ponderei w1 este:
[[-0.4]
 [ 0.4]
 [-0.2]] 

Se aplica x1 : 
Net la pasul 1 este:  [-0.2]
Nu are loc nicio corectie 

Se aplica x2
Net la pasul 2 este:  [-0.2]
Are loc o corectie a ponderilor!
Dupa corectia ponderei w1 este:
[[-0.4]
 [ 0.2]
 [-0.4]] 

Se aplica x1 : 
Net la pasul 1 este:  [-0.2]
Nu are loc nicio corectie 

Se aplica x2
Net la pasul 2 este:  [0.2]
Nu are loc nicio corectie 

Se aplica x1 : 
Net la pasul 1 este:  [-0.2]
Nu are loc nicio corectie 

Se aplica x2
Net la pasul 2 este:  [0.2]
Nu are loc nicio corectie 

