In [7]:
# Invatarea unui neuron prin algoritmi genetici

import numpy as np
import random

x1 = [2,2,2] # Vector de intrare
x2 = [3,3,3]
w = []
Lista = []

d1 = 20 # Output-ul target                     
d2 = 30

m = np.random.randint(2, size = (50,15)) #matricea cu elemente 0 si 1 random
print(m)


a = 0
while a < 30:
    
#Decodificare nr. 1-5

    for i in range (0,50):
        x = 3
        decimal1 = 0       
        if m[i][10] == 1:
            for j in range (11,15):
                if m[i][j] == 1:
                    decimal1 = decimal1 + (1 * 2)**x
                    x = x - 1
                else:
                    x = x - 1
                    
            w.append(decimal1)
            
        else:
            for j in range (11,15):
                if m[i][j] == 1:
                    decimal1 = decimal1 + (1 * 2)**x
                    x = x - 1
                else:
                    x = x - 1
                    
            decimal1 = decimal1 * (-1) 
            w.append(decimal1)
            
#Decodificare nr. 6-10               
        x = 3
        decimal2 = 0
        if m[i][5] == 1:
            for j in range (6,10):
                if m[i][j] == 1:
                    decimal2 = decimal2 + (1 * 2)**x
                    x = x - 1
                else:
                    x = x - 1
            w.append(decimal2)
        else:
            for j in range (6,10):
                if m[i][j] == 1:
                    decimal2 = decimal2 + (1 * 2)**x
                    x = x - 1
                else:
                    x = x - 1
            
                
            decimal2 = decimal2 * (-1) 
            w.append(decimal2)

#Decodificare nr. 11 - 15
        x = 3
        decimal3 = 0
        if m[i][0] == 1:
            for j in range (1,5):
                if m[i][j] == 1:
                    decimal3 = decimal3 + (1 * 2)**x
                    x = x - 1
                else:
                    x = x - 1
            w.append(decimal3)
        else:
            for j in range (1,5):
                if m[i][j] == 1:
                    decimal3 = decimal3 + (1 * 2)**x
                    x = x - 1
                else:
                    x = x - 1
            
                
            decimal3 = decimal3 * (-1)
            w.append(decimal3)
        
        out1 = (x1[0] * int(w[0])) + (x1[1] * int(w[1])) + (x1[2] * int(w[2]))
        out2 = (x2[0] * int(w[0])) + (x2[1] * int(w[1])) + (x2[2] * int(w[2]))

        F = (abs(d1 - out1) / d1) + (abs(d2 - out2) / d2)
        Lista.append(F)
        
        del w[:]
        
    print(Lista)
    for num in range(len(Lista)-1,0,-1): 
        for i in range(num):
            if Lista[i]>Lista[i+1]:
                temp = Lista[i]
                Lista[i] = Lista[i+1]
                Lista[i+1] = temp
                for j in range(0,15): 
                    temp1 = m[i][j]
                    temp2= m[i+1][j]
                    m[i][j] = temp2
                    m[i+1][j] = temp1
    print("\n\nLista dupa ranking ------->\n\n",Lista)
    
    
    if Lista[0] == 0:
        print("Au fost gasite weight-urile cerute")
        break
    del Lista[:]

    k = 46
    for i in range(0,4):
        for j in range(0,15):
            m[k][j] = m[i][j]
        k += 1
        
    n = random.sample(range(2 , 49), 20)
    i = 0
    while i < 19:
        for j in range (7,15):
            temp1 = m[n[i]][j]
            temp2 = m[n[i+1]][j]
            m[n[i]][j] = temp2
            m[n[i+1]][j] = temp1
        i = i + 2
        
    r1 = random.sample(range(2 , 49), 5)
    r2 = random.sample(range(0 , 15), 5)

    i = 0
    j = 0
    while i < 5:
        temp1 = m[r1[i]][r2[j]]
        temp2 = m[r1[i] + 1][[r2[j]]]
        m[r1[i]][r2[j]] = temp2
        m[r1[i] + 1][[r2[j]]] = temp1
        i = i + 1
        j = j + 1
    a = a + 1



[[0 1 1 0 0 0 1 0 0 1 0 1 1 1 0]
 [1 1 0 1 0 1 0 1 1 1 0 0 0 1 1]
 [0 1 0 0 0 0 1 0 0 0 0 0 0 1 0]
 [1 1 1 1 0 1 0 1 1 1 0 0 1 1 1]
 [1 0 1 1 1 1 1 1 0 1 0 1 0 1 1]
 [1 1 0 0 0 0 0 0 0 0 1 0 1 0 0]
 [0 0 1 1 1 1 1 1 1 0 1 0 1 0 0]
 [0 0 0 1 1 1 1 1 1 1 0 0 1 0 1]
 [0 0 0 1 1 0 0 0 1 1 1 1 0 1 1]
 [0 1 1 0 1 0 1 0 1 0 0 0 0 1 1]
 [1 1 0 0 0 1 1 0 1 0 1 0 1 1 0]
 [1 1 1 1 0 0 1 1 1 0 0 0 1 1 0]
 [1 0 1 0 0 0 0 0 0 0 1 1 1 0 0]
 [0 1 0 0 1 1 1 0 1 1 1 1 1 1 1]
 [0 0 0 0 0 1 0 0 0 0 1 0 1 0 0]
 [1 0 0 0 1 0 1 0 0 1 0 1 1 1 0]
 [1 1 0 1 1 0 1 1 0 0 1 1 1 0 1]
 [1 0 0 1 0 0 1 1 0 1 1 1 0 1 1]
 [1 1 1 0 0 0 1 1 0 0 1 1 0 1 1]
 [1 0 0 1 0 1 0 1 0 1 0 0 0 1 0]
 [0 1 0 1 0 0 1 0 0 0 0 1 0 1 1]
 [1 0 0 1 0 0 0 1 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 0 1 1 1 0 1 0 0 0]
 [1 1 0 0 0 1 1 0 1 1 1 0 1 0 0]
 [0 0 0 1 1 0 1 0 0 0 1 0 1 1 0]
 [1 1 0 0 0 1 1 0 1 1 1 0 1 1 0]
 [1 0 1 0 0 1 0 1 0 0 1 1 1 0 1]
 [0 0 1 0 1 1 0 1 1 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 1 0 1 0 0 1 0]
 [1 0 0 1 0 0 1 0 0 0 1 1 1 1 0]
 [1 1 1 1 